default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root_dev
  password: 1234
  socket: /var/run/mysqld/mysqld.sock

development:
  <<: *default
  database: ror_cms_development


#test:
#  <<: *default
#  database: ror_cms

#production:
#  <<: *default
#  database: ror_cms
