production:
  adapter: postgresql
  encoding: unicode
  database: indorails_pro
  pool: 5
  username: postgres
  password: Indorails1945
  host: localhost
  
development:
  adapter: postgresql
  encoding: unicode
  database: indorails_dev
  pool: 5
  username: postgres_dev
  password: 1234
  host: localhost
  
test:
  adapter: postgresql
  encoding: unicode
  database: indorails_test
  pool: 5
  username: postgres_dev
  password: 1234
  host: localhost
