# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5f5ac5da5971f441b50db5cf246e9a83207cf389bd6b0dc26c769651783549b2f76aa4d3ad7f9cd20651081a45af38d77f5f73f955726f8271c4c3c67fb5b9a4

test:
  secret_key_base: 284a367b96f758a9c2619e499d41a6757a140f66eb53ac3e5eb1a72b479a9f4019ad89dd1d765f4395e8baa2cc0964773dea478c73682ce06061dd90b3e50159

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  #secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  secret_key_base: "291696de0199edec5f9951a178b126147e43ee3f46f3e5fbcdfc9f1926f3a16c31a3bf1a9604c4961f09d7aad00fad5c3fed09715bd6ab4014a68659d5ca0228"
